// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnD7A60-fTdxBJTwobEpxYiNeO_qWILS8',
    appId: '1:396443299638:web:09224ac5410ce0a11e0d97',
    messagingSenderId: '396443299638',
    projectId: 'flutterfire-flash-chat',
    authDomain: 'flutterfire-flash-chat.firebaseapp.com',
    storageBucket: 'flutterfire-flash-chat.appspot.com',
    measurementId: 'G-88ZVZ0WBQ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZQyjLD--U3BsPsekgBu-Zqo30jpKmLKM',
    appId: '1:396443299638:android:f948713057ea4fae1e0d97',
    messagingSenderId: '396443299638',
    projectId: 'flutterfire-flash-chat',
    storageBucket: 'flutterfire-flash-chat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzQIhZWWvQbye9jrMxDEhKECRoVoMxS38',
    appId: '1:396443299638:ios:eada0a1f5cef25eb1e0d97',
    messagingSenderId: '396443299638',
    projectId: 'flutterfire-flash-chat',
    storageBucket: 'flutterfire-flash-chat.appspot.com',
    iosBundleId: 'com.noahwons.flutterfireFlashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzQIhZWWvQbye9jrMxDEhKECRoVoMxS38',
    appId: '1:396443299638:ios:eada0a1f5cef25eb1e0d97',
    messagingSenderId: '396443299638',
    projectId: 'flutterfire-flash-chat',
    storageBucket: 'flutterfire-flash-chat.appspot.com',
    iosBundleId: 'com.noahwons.flutterfireFlashChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnD7A60-fTdxBJTwobEpxYiNeO_qWILS8',
    appId: '1:396443299638:web:6b74196017b398141e0d97',
    messagingSenderId: '396443299638',
    projectId: 'flutterfire-flash-chat',
    authDomain: 'flutterfire-flash-chat.firebaseapp.com',
    storageBucket: 'flutterfire-flash-chat.appspot.com',
    measurementId: 'G-7G5VHZDSPL',
  );
}
